// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOY29xNuwgLR5fNKRdMWl1Pbgl0sM5EdQ',
    appId: '1:355206687889:web:e8acc0f36fd26450b7e330',
    messagingSenderId: '355206687889',
    projectId: 'medicart-f5510',
    authDomain: 'medicart-f5510.firebaseapp.com',
    storageBucket: 'medicart-f5510.firebasestorage.app',
    measurementId: 'G-MGKGQGNH3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPHq8A5LttU5U0ps-3XEyiJvLF85GpHSw',
    appId: '1:355206687889:android:f1121ee1e6bbcd7fb7e330',
    messagingSenderId: '355206687889',
    projectId: 'medicart-f5510',
    storageBucket: 'medicart-f5510.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVw9Jl2I0w3vV3Ate2l0cb3G82k35rSnk',
    appId: '1:355206687889:ios:ec2771f9e9685cccb7e330',
    messagingSenderId: '355206687889',
    projectId: 'medicart-f5510',
    storageBucket: 'medicart-f5510.firebasestorage.app',
    iosBundleId: 'com.example.medicart',
  );
}
